apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      k8s-app: {name}
    name: {name}
  spec:
    replicas: 1 # dev set 1 for debug,  modify it to fit prod
    selector:
      matchLabels:
        k8s-app: {name}
    # strategy:               # comments it since RollingUpdate is the default strategy
    #   type: RollingUpdate   # otherwise it will lead `configured` when do `kubectl apply`
    template:
      metadata:
        labels:
          k8s-app: {name}
      spec:
        containers:
        - env:
          # here add enviromment variable
          image: {image-path}
          imagePullPolicy: Always
          name: {name}
          resources:
            requests:
              cpu: 100m  # modify resource request to fit prod
              memory: 128Mi
        dnsPolicy: ClusterFirst
        restartPolicy: Always

- apiVersion: v1
  kind: Service
  metadata:
    name: {name}
  spec:
    ports:
    - name: {port}-{port}-tcp
      port: {port}
      protocol: TCP
      targetPort: {port}
    selector:
      k8s-app: {name}
    sessionAffinity: None
    type: NodePort  # important !!!
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: {name}-ingress-443
  spec:
    rules:
    - host: {ingress-host}
      http:
        paths:
          - path: /   # TKE does not like `/*`
            pathType: Prefix
            backend:
              service:
                name: {name}
                port:
                  number: {port}

# - apiVersion: networking.k8s.io/v1beta1
#   kind: Ingress
#   metadata:
#     name: {name}-ingress-443
#   spec:
#     rules:
#     - host: {ingress-host}
#       http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: {name}
#               servicePort: {port}             

kind: List


